export const siteConfig = {
  name: 'Civitech Commune SaaS',
  municipality: 'Niakaramadougou',
  apiBaseUrl: process.env.NEXT_PUBLIC_API_BASE_URL || 'http://localhost:3005',
  sections: [
    { href: '/', label: 'Accueil' },
    { href: '/commune', label: 'Portail' },
    { href: '/commune/espace-citoyen', label: 'Espace citoyen' },
    { href: '/commune/mes-brouillons', label: 'Mes brouillons' },
    { href: '/commune/mes-dossiers-soumis', label: 'Mes dossiers soumis' },
    { href: '/commune/agent-dossiers', label: 'Vue agent' },
    { href: '/commune/agent-validation-documents', label: 'Validation docs' },
    { href: '/commune/admin', label: 'Admin mock' },
    { href: '/commune/admin-console', label: 'Admin connecte' },
    { href: '/commune/admin-gestion', label: 'Admin gestion' },
    { href: '/commune/admin-crud', label: 'Admin CRUD' },
    { href: '/commune/demarches', label: 'Demarches' },
    { href: '/commune/demarches/declaration-naissance', label: 'Naissance' },
    { href: '/commune/demarches/demande-copie-acte', label: 'Copie acte' },
    { href: '/commune/demarches/declaration-deces', label: 'Deces' },
    { href: '/commune/demarches/organisation-mariage', label: 'Mariage' },
    { href: '/commune/dossiers-connectes', label: 'Dossiers connectes' },
    { href: '/auth/demo-login', label: 'Demo login' },
  ],
};
